// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://parbgfvfaelkwaghgqcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcmJnZnZmYWVsa3dhZ2hncWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODAyMTcsImV4cCI6MjA3MzQ1NjIxN30.u71gW2vEIOvAAtBsXabv7gJEbN9-ivgJPizC6T0bjwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});